### ISSUE TITLE
train_model.py doesn't function well

### ISSUE THREAD

**Issue by PANDASANG1231** [PANDASANG1231/522_Ramen#38]
It is reported that there is an error while running the code. 

```
python src/train_model.py --train_file="data/process/train_process.csv" --out_file_train="results/best_model.pkl"
/Users/allyson/School/Block-3/522_Ramen/src/train_model.py:69: DtypeWarning: Columns (647) have mixed types.Specify dtype option on import or set low_memory=False.
 main(opt["--train_file"], opt["--out_file_train"])
Traceback (most recent call last):
 File "/Users/allyson/School/Block-3/522_Ramen/src/train_model.py", line 69, in <module>
  main(opt["--train_file"], opt["--out_file_train"])
 File "/Users/allyson/School/Block-3/522_Ramen/src/train_model.py", line 44, in main
  train_data["Stars"] = train_data["Stars"].replace("Unrated", -1).astype(float).apply(handle_target)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/generic.py", line 5815, in astype
  new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 418, in astype
  return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 327, in apply
  applied = getattr(b, f)(**kwargs)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 591, in astype
  new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
  new_values = astype_array(values, dtype, copy=copy)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
  values = astype_nansafe(values, dtype, copy=copy)
 File "/opt/miniconda3/envs/522_Group6/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1201, in astype_nansafe
  return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'NR'
make: *** [results/best_model.pkl] Error 1

```

**Comment by PANDASANG1231** [comment]
I changed the original code into, the problem is fixed and should be more robust.
```
pd.to_numeric(data[target_name], errors='coerce')
```
